/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Adaptadores.ConectorDB;
import Dominio.Cliente;
import Dominio.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author alexd
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    ConectorDB conector;
    JPanel nuevoPanel;
    ArrayList<String> permisos;

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal(ConectorDB conector, String usuario) {
        this.conector= conector;
        permisos = new ArrayList<String>();
        try{
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }catch(Exception e){
            e.printStackTrace();
        } 
        initComponents();
        Usuario.llenarPrivilegios(conector, permisos, usuario);
        menuModeloAviones.setVisible(permisos.contains("rmodelo_aeronave"));
        menuAviones.setVisible(permisos.contains("raeronave"));
        menuLotes.setVisible(permisos.contains("rlote_material"));
        menuInventario.setVisible(permisos.contains("rinventario"));
        separador1.setVisible(permisos.contains("rmodelo_aeronave")||permisos.contains("raeronave")
                              ||permisos.contains("rlote_material")||permisos.contains("rinventario")
        );
        menuComprar.setVisible(permisos.contains("clote_material"));
        menuVender.setVisible(permisos.contains("caeronave"));
        menuFactura.setVisible(permisos.contains("rfactura"));
        separador2.setVisible(permisos.contains("clote_material")||permisos.contains("caeronave")
                              ||permisos.contains("rfactura")
        );
        menuClientes.setVisible(permisos.contains("rcliente"));
        menuProveedores.setVisible(permisos.contains("rproveedor"));
        menuUsuario.setVisible(permisos.contains("rusuario"));
        separador3.setVisible(permisos.contains("rcliente")||permisos.contains("rproveedor")
                              ||permisos.contains("rusuario")
        );
        menuReporte.setVisible(permisos.contains("rreporte"));
        separador4.setVisible(permisos.contains("rreporte")
        );
        jlUsuario.setText(usuario);
        Contenido.setVisible(false);
        panelMensaje.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMensaje = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        LateralExpandido = new javax.swing.JPanel();
        panelLateralExtendido = new javax.swing.JPanel();
        menuInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        separador1 = new javax.swing.JLabel();
        menuModeloAviones = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        menuAviones = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        menuLotes = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        menuInventario = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        separador2 = new javax.swing.JLabel();
        menuComprar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        menuVender = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        menuFactura = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        separador3 = new javax.swing.JLabel();
        menuClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        menuProveedores = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        menuUsuario = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        separador4 = new javax.swing.JLabel();
        menuReporte = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        fondoLateralExpandido = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        fondoContenido = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 715));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_check_black_24dp_1x.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel22.setText("sfd");

        javax.swing.GroupLayout panelMensajeLayout = new javax.swing.GroupLayout(panelMensaje);
        panelMensaje.setLayout(panelMensajeLayout);
        panelMensajeLayout.setHorizontalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        panelMensajeLayout.setVerticalGroup(
            panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensajeLayout.createSequentialGroup()
                .addGroup(panelMensajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(panelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 685, 600, 24));

        LateralExpandido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLateralExtendido.setOpaque(false);

        menuInicio.setOpaque(false);
        menuInicio.setPreferredSize(new java.awt.Dimension(162, 30));
        menuInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuInicioFocusGained(evt);
            }
        });
        menuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInicioMouseClicked(evt);
            }
        });
        menuInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(66, 66, 66));
        jLabel1.setText("Inicio");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        menuInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_home_black_24dp_1x.png"))); // NOI18N
        menuInicio.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        separador1.setBackground(new java.awt.Color(0, 0, 0));
        separador1.setOpaque(true);

        menuModeloAviones.setOpaque(false);
        menuModeloAviones.setPreferredSize(new java.awt.Dimension(162, 30));
        menuModeloAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuModeloAvionesMouseClicked(evt);
            }
        });
        menuModeloAviones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(66, 66, 66));
        jLabel25.setText("Modelos de Avion");
        jLabel25.setToolTipText("");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        menuModeloAviones.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_widgets_black_24dp_1x.png"))); // NOI18N
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuModeloAviones.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        menuAviones.setOpaque(false);
        menuAviones.setPreferredSize(new java.awt.Dimension(162, 30));
        menuAviones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAvionesMouseClicked(evt);
            }
        });
        menuAviones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(66, 66, 66));
        jLabel14.setText("Aviones");
        jLabel14.setToolTipText("");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        menuAviones.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/avion.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuAviones.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        menuLotes.setOpaque(false);
        menuLotes.setPreferredSize(new java.awt.Dimension(162, 30));
        menuLotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLotesMouseClicked(evt);
            }
        });
        menuLotes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(66, 66, 66));
        jLabel23.setText("Lotes");
        jLabel23.setToolTipText("");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        menuLotes.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_crop_square_black_24dp_1x.png"))); // NOI18N
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuLotes.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        menuInventario.setOpaque(false);
        menuInventario.setPreferredSize(new java.awt.Dimension(162, 30));
        menuInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuInventarioMouseClicked(evt);
            }
        });
        menuInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(66, 66, 66));
        jLabel12.setText("Inventario");
        jLabel12.setToolTipText("");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        menuInventario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_inbox_black_24dp_1x.png"))); // NOI18N
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuInventario.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        separador2.setBackground(new java.awt.Color(0, 0, 0));
        separador2.setOpaque(true);

        menuComprar.setOpaque(false);
        menuComprar.setPreferredSize(new java.awt.Dimension(162, 30));
        menuComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuComprarMouseClicked(evt);
            }
        });
        menuComprar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(66, 66, 66));
        jLabel8.setText("Comprar Materiales");
        jLabel8.setToolTipText("");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        menuComprar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_local_shipping_black_24dp_1x.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuComprar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        menuVender.setOpaque(false);
        menuVender.setPreferredSize(new java.awt.Dimension(162, 30));
        menuVender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuVenderMouseClicked(evt);
            }
        });
        menuVender.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(66, 66, 66));
        jLabel10.setText("Vender Avion");
        jLabel10.setToolTipText("");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        menuVender.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_flight_land_black_24dp_1x.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuVender.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        menuFactura.setOpaque(false);
        menuFactura.setPreferredSize(new java.awt.Dimension(162, 30));
        menuFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFacturaMouseClicked(evt);
            }
        });
        menuFactura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(66, 66, 66));
        jLabel19.setText("Facturas");
        jLabel19.setToolTipText("");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        menuFactura.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_attach_money_black_24dp_1x.png"))); // NOI18N
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuFactura.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        separador3.setBackground(new java.awt.Color(0, 0, 0));
        separador3.setOpaque(true);

        menuClientes.setOpaque(false);
        menuClientes.setPreferredSize(new java.awt.Dimension(162, 30));
        menuClientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                menuClientesFocusGained(evt);
            }
        });
        menuClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuClientesMouseClicked(evt);
            }
        });
        menuClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(66, 66, 66));
        jLabel4.setText("Clientes");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        menuClientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_business_center_black_24dp_1x.png"))); // NOI18N
        menuClientes.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 24, 24));

        menuProveedores.setOpaque(false);
        menuProveedores.setPreferredSize(new java.awt.Dimension(162, 30));
        menuProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProveedoresMouseClicked(evt);
            }
        });
        menuProveedores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(66, 66, 66));
        jLabel3.setText("Proveedores");
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        menuProveedores.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_store_black_24dp_1x.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuProveedores.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        menuUsuario.setOpaque(false);
        menuUsuario.setPreferredSize(new java.awt.Dimension(162, 30));
        menuUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUsuarioMouseClicked(evt);
            }
        });
        menuUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(66, 66, 66));
        jLabel27.setText("Usuarios y Roles");
        jLabel27.setToolTipText("");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        menuUsuario.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_person_black_24dp_1x.png"))); // NOI18N
        jLabel28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuUsuario.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        separador4.setBackground(new java.awt.Color(0, 0, 0));
        separador4.setOpaque(true);

        menuReporte.setOpaque(false);
        menuReporte.setPreferredSize(new java.awt.Dimension(162, 30));
        menuReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuReporteMouseClicked(evt);
            }
        });
        menuReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(66, 66, 66));
        jLabel30.setText("Reportes");
        jLabel30.setToolTipText("");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        menuReporte.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 6, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_assignment_black_24dp_1x.png"))); // NOI18N
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuReporte.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, -1, -1));

        javax.swing.GroupLayout panelLateralExtendidoLayout = new javax.swing.GroupLayout(panelLateralExtendido);
        panelLateralExtendido.setLayout(panelLateralExtendidoLayout);
        panelLateralExtendidoLayout.setHorizontalGroup(
            panelLateralExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralExtendidoLayout.createSequentialGroup()
                .addGroup(panelLateralExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLateralExtendidoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLateralExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menuAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
            .addGroup(panelLateralExtendidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLateralExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuModeloAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLateralExtendidoLayout.setVerticalGroup(
            panelLateralExtendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralExtendidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(separador1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuModeloAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuAviones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuComprar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuVender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador4, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        LateralExpandido.add(panelLateralExtendido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 661));

        fondoLateralExpandido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/BarraLateralExtendida.png"))); // NOI18N
        LateralExpandido.add(fondoLateralExpandido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(LateralExpandido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 180, 667));

        Contenido.setOpaque(false);
        Contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido.setBackground(new java.awt.Color(255, 255, 255));
        panelContenido.setMaximumSize(new java.awt.Dimension(870, 610));
        panelContenido.setMinimumSize(new java.awt.Dimension(870, 610));
        panelContenido.setOpaque(false);
        panelContenido.setPreferredSize(new java.awt.Dimension(870, 610));

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        Contenido.add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        fondoContenido.setMaximumSize(new java.awt.Dimension(870, 610));
        fondoContenido.setMinimumSize(new java.awt.Dimension(870, 610));
        fondoContenido.setOpaque(true);
        Contenido.add(fondoContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 610));

        getContentPane().add(Contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 870, 610));

        campoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(campoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 4, 140, 40));

        jlTitulo.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setText("Sistema de Ensamble de Aviones");
        jlTitulo.setToolTipText("");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jlUsuario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlUsuario.setText("jLabel32");
        getContentPane().add(jlUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 90, 24));

        jLabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/ic_account_circle_white_24dp_1x.png"))); // NOI18N
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 24, 24));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/FondoPrincipal.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 710));
        jLabel2.getAccessibleContext().setAccessibleName("Fondo");
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuInicioFocusGained

    }//GEN-LAST:event_menuInicioFocusGained

    private void menuClientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_menuClientesFocusGained
        
    }//GEN-LAST:event_menuClientesFocusGained

    private void menuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalClientes(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
        
    }//GEN-LAST:event_menuClientesMouseClicked

    private void menuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInicioMouseClicked
        Contenido.setVisible(false);
    }//GEN-LAST:event_menuInicioMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Contenido.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalClientes(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void menuProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProveedoresMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalProveedores(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuProveedoresMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalProveedores(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalComprar(conector,Contenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void menuComprarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuComprarMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalComprar(conector,Contenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuComprarMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalVender(conector,Contenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void menuVenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVenderMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalVender(conector,Contenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuVenderMouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalInventario(conector,Contenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void menuInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuInventarioMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalInventario(conector,Contenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuInventarioMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalAviones(conector,panelContenido,panelMensaje,permisos);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void menuAvionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAvionesMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalAviones(conector,panelContenido,panelMensaje,permisos);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuAvionesMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalFactura(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void menuFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFacturaMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalFactura(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuFacturaMouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalLotes(conector,panelContenido,panelMensaje,permisos);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void menuLotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLotesMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalLotes(conector,panelContenido,panelMensaje,permisos);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuLotesMouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalModeloAvion(conector,panelContenido,panelMensaje,permisos);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel25MouseClicked

    private void menuModeloAvionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuModeloAvionesMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalModeloAvion(conector,panelContenido,panelMensaje,permisos);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuModeloAvionesMouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalUsuarios(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel27MouseClicked

    private void menuUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuarioMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalUsuarios(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuUsuarioMouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalReportes(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_jLabel30MouseClicked

    private void menuReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuReporteMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalReportes(conector,panelContenido,panelMensaje);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_menuReporteMouseClicked

    private void campoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoUsuarioMouseClicked
        Contenido.setVisible(true);
        nuevoPanel = new PrincipalDatos(conector,panelContenido,jlUsuario.getText(),panelMensaje, this);
        panelContenido.removeAll();
        panelContenido.add(nuevoPanel);
        panelContenido.updateUI();
    }//GEN-LAST:event_campoUsuarioMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenido;
    private javax.swing.JPanel LateralExpandido;
    private javax.swing.JLabel campoUsuario;
    private javax.swing.JLabel fondoContenido;
    private javax.swing.JLabel fondoLateralExpandido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JPanel menuAviones;
    private javax.swing.JPanel menuClientes;
    private javax.swing.JPanel menuComprar;
    private javax.swing.JPanel menuFactura;
    private javax.swing.JPanel menuInicio;
    private javax.swing.JPanel menuInventario;
    private javax.swing.JPanel menuLotes;
    private javax.swing.JPanel menuModeloAviones;
    private javax.swing.JPanel menuProveedores;
    private javax.swing.JPanel menuReporte;
    private javax.swing.JPanel menuUsuario;
    private javax.swing.JPanel menuVender;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelLateralExtendido;
    private javax.swing.JPanel panelMensaje;
    private javax.swing.JLabel separador1;
    private javax.swing.JLabel separador2;
    private javax.swing.JLabel separador3;
    private javax.swing.JLabel separador4;
    // End of variables declaration//GEN-END:variables
  

}
